pygments: true
permalink: /:year/:month/:day/:title
markdown: rdiscount
exclude: ['.git']
name: "Pippi's Magic Box"
description: "A party space for all of us. Just come and chill"
url: https://pippi.blog
